# Generated by Django 4.0.2 on 2022-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('owner', models.TextField()),
            ],
        ),
    ]
