# Generated by Django 3.0 on 2022-03-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="cover",
            field=models.FileField(upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="files",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="files",
            name="owner",
            field=models.CharField(max_length=30),
        ),
    ]
