# Generated by Django 3.2.12 on 2022-03-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_auto_20220303_1646"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
