# Generated by Django 4.0.2 on 2022-03-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_files_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
